### ISSUE TITLE
ncm2-jedi is not work

### ISSUE THREAD

**Issue by holenlv** [ncm2/ncm2-jedi#5]
I add ncm2-jedi and ncm2-go,ncm2-go works well
when I open new python file , it just tell me
  [ncm2_jedi@yarp] Job is dead. cmd=['/usr/local/opt/python/bin/python3.7', '-u',.......

**Comment by roxma** [comment]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### neovim `:version` output

### Minimal vimrc for reproducing the issue

### neovim `:messages` output when the error occurs

### Log files if you think the issue is a bug

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

**Comment by holenlv** [comment]
thanks,I read neovim: messages I  find the solution,I forget to  install jedi
